# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504c093793248d53ca3c0d0689bfeb4f1c2521267a1fa59c4edc60709908241de48874c7f0b36487f7786da1720a1efaa25dddde669ab1abca6484194b5d96ca

test:
  secret_key_base: e7083698005939bc718a6aae6cbf48477de31c82eef1d61db315c39d79745269e968b383db68a10860f2bcfe3774aefdc0ee69d8c45faa0295263ece596725da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
