Contact.create!(name: "Name 1", address: "Address 1", phonenumber: "111 11 11 11", email: "email1@ironhack.com", favorite: false)
Contact.create!(name: "Name 2", address: "Address 2", phonenumber: "222 22 22 22", email: "email2@ironhack.com", favorite: false)
Contact.create!(name: "Name 3", address: "Address 3", phonenumber: "333 33 33 33", email: "email3@ironhack.com", favorite: false)
Contact.create!(name: "Name 4", address: "Address 4", phonenumber: "444 44 44 44", email: "email4@ironhack.com", favorite: false)
Contact.create!(name: "Name 5", address: "Address 5", phonenumber: "555 55 55 55", email: "email5@ironhack.com", favorite: false)